services:
  api-service:
    build:
      context: .
      dockerfile: "Minimal API/Dockerfile"
    container_name: rsvp-api
    environment:
      - AI__ApiKey=${AI_API_KEY}
    networks:
      - private-network
      - npm-network
    restart: always

  web-app:
    build:
      context: .
      dockerfile: "WEB/Dockerfile"
    container_name: rsvp-web
    depends_on:
      - api-service
    networks:
      - npm-network

    restart: always

networks:
  private-network:
    external: true
    name: private-network

  npm-network:
    external: true
    name: npm-network

